setwp_test:
  ros__parameters:
    waypoints_names: ["init", "tv", "bathroom1", "bathroom2", "bedroom1", "bedroom2", "kitchen", "table"]
    waypoints:
      init: [0.0, 0.0, 0.0]
      bathroom1: [-1.85, 3.0, 0.0]
      bathroom2: [-4.5, -0.6, 0.0]
      bedroom1: [-4.6, 1.75, 0.0]
      bedroom2: [-4.0, -4.0, 0.0]
      kitchen: [1.68, -2.6, 0.0]
      tv: [3.5, -0.5, 0.0]
      table: [4.5, 3.0, 0.0]