setwp_and_moveto_test:
  ros__parameters:
    waypoints_names: ["entrance", "tv", "bathroom"]
    waypoints:
      entrance: [5.4, 2.8, 0.0]
      bathroom: [-1.85, 3.0, 0.0]
      tv: [3.5, -0.5, 0.0]
      inspection: [0.0, 0.0, 0.0]