behaviors_main:
  ros__parameters:
    use_sim_time: False
    cam_frame: "head_front_camera_color_optical_frame"
    home_position: [54.701, 1.360, 0.001]
    home_pose: "home"
    offer_pose: "offer"
    person_id: 001122334455
    bt_xml_file: gpsr.xml
    waypoints_names:
      [
        "shelf",
        "kitchen_table",
        "cabinet",
        "desk",
        "armchair",
        "sofa",
        "bookshelf",
        "entrance",
        "exit",
        "kitchen",
        "office",
        "living_room",
        "instruction_point"
      ]
    waypoints:
      shelf: [1.101, -7.614, -0.404]
      kitchen_table: [-0.241, -7.820, -2.086]
      cabinet: [-1.101, -7.614, -0.404]
      desk: [0.208, -4.235, 0.00]
      armchair: [-1.100, -2.385, -2.00]
      sofa: [-4.028, -5.738, 1.067]
      bookshelf: [1.101, -7.614, -0.404]
      entrance: [-1.775, -1.398, -1.8]
      exit: [1.247, -3.918, 1.039]
      kitchen: [0.227, -6.983, -1.978]
      office: [1.398, -4.949, 2.5]
      living_room: [-2.725, -3.593, -2.210]
      instruction_point: [-2.725, -3.593, -2.210]
    plugins:
      - dialogConfirmation_bt_node
      - listen_bt_node
      - follow_entity_bt_node
      - speak_bt_node
      - deferred_bt_node
      - set_wp_bt_node
      - command_planning_bt_node
      - setup_gpsr_bt_node
      - set_start_position_bt_node
      - move_to_bt_node
      - start_music_bt_node
      - stop_music_bt_node
      - is_door_open_bt_node
