behaviors_main:
  ros__parameters:
    use_sim_time: False
    cam_frame: "head_front_camera_link_color_optical_frame"
    home_position: [54.701, 1.360, 0.001]
    home_pose: "home"
    offer_pose: "offer"
    person_id: 001122334455
    bt_xml_file: gpsr.xml
    waypoints_names:
      [
        "tv_table",
        "hallway",
        "hallway_cabinet",
        "desk",
        "shelf",
        "coathanger",
        "lounge_chair",
        "lamp",
        "couch",
        "trashcan",
        "kitchen_cabinet",
        "dinner_table",
        "kitchen_counter",
        "dishwasher",
        "entrance",
        "coffee_table",
        "exit",
        "kitchen",
        "office",
        "living_room",
        "instruction_point"
      ]
    waypoints:
      #ARENA B
      tv_table: [-14.936, -0.490, 1.543]
      hallway: [-12.272, 0.691, 2.076]
      hallway_cabinet: [-14.214, 2.942, 1.258]
      desk: [-9.134, 2.014, 2.901]
      shelf: [-8.354, 0.573, 1.306]
      coathanger: [-12.637, 2.190, -0.207] 
      lounge_chair: [-14.914, -2.117, -2.731]
      lamp: [-14.902, -1.983, -2.276]
      couch: [-13.489, -1.594, -2.120]
      trashcan: [3.79, 6.77, 0.12] #TODO
      kitchen_cabinet: [-8.263, -1.846, 1.239]
      dinner_table: [-9.216, -1.555, -1.775]
      kitchen_counter: [-9.312, -4.550, -1.747]
      dishwasher: [-10.371, -4.185, -1.762]
      entrance: [-11.886, 2.915, 1.952]
      coffee_table: [-14.142, -2.027, -2.056]
      exit: [-8.242, -0.344, -0.441]
      kitchen: [-11.626, -0.85, -0.689]
      office: [-8.551, 0.033, 2.090]
      living_room: [-13.452, -1.870, -2.397]
      instruction_point: [-12.933, -0.495, -2.132]
    plugins:
      - dialogConfirmation_bt_node
      - listen_bt_node
      - follow_entity_bt_node
      - speak_bt_node
      - deferred_bt_node
      - set_wp_bt_node
      - command_planning_bt_node
      - setup_gpsr_bt_node
      - set_start_position_bt_node
      - move_to_bt_node
      - start_music_bt_node
      - stop_music_bt_node
      - is_door_open_bt_node


# ARENA B:

# GPSR: 
# -14.936, -0.490 1.543 TV_TABLE
# -14.142, -2.027, -2.056 COFFEE TABLE
#-14.914, -2.117, -2.731 LOUNGE_CHAIR
# -12.637, 2.190, -0.207 COAT HANGER
# -14.214, 2.942, 1.258 HALLWAY CABINET
# -9.134, 2.014, 2.901 DESK
# -8.354, 0.573, 1.306 SHELF
# -13.489, -1.594, -2.120 COUCH
# -14.902, -1.983, -2.276 LAMP
# -10.371, -4.185, -1.762 DISHWASHER
# -9.312, -4.550, -1.747 KITCHEN COUNTER
# -9.216, -1.555, -1.775 DINNER TABLE
# -11.626, -0.85, -0.689 KITCHEN
# -13.452, -1.870, -2.397 LIVING ROOM
# -8.551, 0.033 2.090 OFFICE
# -12.272, 0.691 2.076 HALLWAY




# STORING:



# ARENA C:

# STORING 
#   (pitch -0.19435251909188134 rads y el torso 0.3703573383376339 m )place position
