/**:
  ros__parameters:
    use_sim_time: False
    allow_duplicate_names: true

attention_server:
  ros__parameters:
    period: 0.05
    max_yaw: 1.3
    max_pitch: 0.3 #0.185
    max_vel_yaw: 0.01
    max_vel_pitch: 0.01

perception_people_detection:
  ros__parameters:
    target_frame: base_footprint
    debug: true

perception_objects_detection:
  ros__parameters:
    target_frame: base_footprint
    debug: true

