/**:
  ros__parameters:
    use_sim_time: false
    allow_duplicate_names: true

attention_server:
  ros__parameters:
    period: 0.05
    max_yaw: 1.3
    max_pitch: 0.185
    max_vel_yaw: 0.5
    max_vel_pitch: 0.5

perception_people_detection:
  ros__parameters:
<<<<<<< HEAD
    target_frame: head_front_camera_rgb_frame
=======
    target_frame: head_front_camera_link_color_optical_frame
    debug: true

perception_objects_detection:
  ros__parameters:
    target_frame: head_front_camera_link_color_optical_frame
>>>>>>> coresense/adaptation_cascade
    debug: true

