/**:
  ros__parameters:
    use_sim_time: False
    cam_frame: "head_front_camera_link_color_optical_frame"
    home_position: [0.0, 0.0, 0.0]
    home_pose: "home"
    offer_pose: "offer"
    person_id: 001122334455
    waypoints_names: ["entrance", "party"]
    # allow_duplicate_names: false
    waypoints:
      entrance: [-1.4, 6.82, 0.0]
      party: [-0.2, 4.33, 0.0]