/**:
  ros__parameters:
    use_sim_time: False
    cam_frame: "head_front_camera_rgb_optical_frame"
    home_position: [0.0, 0.0, 0.0]
    home_pose: "home"
    offer_pose: "offer"
    waypoints_names: ["entrance", "table", "secure_pick", "cabinet", "secure_place"]
    # ARENA C:
    waypoints:
      entrance: [-0.711, -0.612, -3.078]
      table: [14.965, -5.944, 1.752]
      secure_pick: [5.567, 2.208, 1.9218]
      cabinet: [12.921, -3.735, -2.987]
      secure_place: [4.968, 2.2, 1.824]
    # ARENA B:
    # waypoints: # [x, y, yaw] only 3 numbers!!
    #   entrance: [-0.711, -0.612, -3.078]
    #   table: [-11.251, -2.897, -0.245]
    #   secure_pick: [5.567, 2.208, 1.9218]
    #   cabinet: [-8.263, -1.846, 1.239]
    #   secure_place: [4.968, 2.2, 1.824]

behaviors_main:
  ros__parameters:
    use_sim_time: False
    bt_xml_file: storing_groceries.xml
    plugins:
    - set_wp_bt_node
    - move_to_bt_node
    - is_detected_bt_node
    - pan_bt_node
    - speak_bt_node
    - is_door_open_bt_node
    - dialogConfirmation_bt_node
    - move_to_predefined_bt_node
    - move_joint_bt_node
    - extract_object_from_scene_bt_node
    - generate_text_from_objects_bt_node
    - extract_collision_scene_bt_node
    - pick_bt_node
    - choose_from_classes_bt_node
    - extract_cabinet_place_pose_bt_node
    - place_bt_node
    - init_groceries_bt_node
    - point_at_bt_node
    - clear_octomap_bt_node
    - remove_string_suffix_bt_node
    - extract_pc_from_class_bt_node
    - pick_object_from_pc_bt_node
    - move_end_effector_bt_node
    - generate_grasp_poses_bt_node
    - move_along_axis_bt_node
