behaviors_main:
  ros__parameters:
    use_sim_time: False
    cam_frame: "head_front_camera_link_color_optical_frame"
    home_position: [0.0, 0.0, 0.0]
    home_pose: "home"
    offer_pose: "offer"
    person_id: 001122334455
    bt_xml_file: carry_my_luggage.xml
    plugins:
    - speak_bt_node
    - listen_bt_node
    - dialogConfirmation_bt_node
    - init_carry_bt_node
    - is_entity_moving_bt_node
    - is_detected_bt_node
    - is_pointing_bt_node
    - move_to_bt_node
    - move_to_predefined_bt_node
    - look_at_bt_node
