/**:
  ros__parameters:
    use_sim_time: False
    cam_frame: "head_front_camera_link_color_optical_frame"
    home_position: [0.0, 0.0, 0.0]
    home_pose: "home"
    offer_pose: "offer"
    host_drink: "Coke"
    host_name: "Irene"
    person_id: 001122334455
    waypoints_names: ["entrance", "party"]
    waypoints:
      entrance: [-0.711, -0.912, -3.078]
      party: [0.887, -0.932, -1.686]
