name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    # Run in the ROS 2 Humble image of ros-tooling
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nlohmann-json3-dev libunwind-dev libgoogle-glog-dev \
            libatlas-base-dev libsuitesparse-dev libgflags-dev libceres-dev
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.8
        with:
          package-name: arm bt_test hri motion perception robocup_bringup
          target-ros2-distro: humble
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          vcs-repo-file-url: ${{ github.workspace }}/robocup_bringup/thirdparty.repos
