name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    env:
      # Tests cannot create ~/.ros/log in the runner
      ROS_LOG_DIR: /tmp/ros_log
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.19
        with:
          required-ros-distributions: humble
      - name: Install nlohmann
        run: sudo apt -y install nlohmann-json3-dev
      - name: Install ceres dependencies
        run: sudo apt -y install libunwind-dev libgoogle-glog-dev libatlas-base-dev libsuitesparse-dev libgflags-dev
      - name: Install ceres
        run: sudo apt -y install libceres-dev
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.8
        with:
          package-name: arm bt_test hri motion perception robocup_bringup cs4home_core
          target-ros2-distro: humble
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          vcs-repo-file-url: ${{ github.workspace }}/robocup_bringup/thirdparty.repos
